[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/responses"
  to = "/.netlify/functions/api-responses"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/api-register"
  status = 200

[[redirects]]
  from = "/api/responses/summary"
  to = "/.netlify/functions/api-responses-summary"
  status = 200
